window.SONGS = [
  {"artist": "ACRAZE", "title": "Do It To It ft. Cherish", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "a-ha", "title": "Take On Me", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "a-ha", "title": "Take On Me", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "AJR", "title": "Bang", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Al Green", "title": "Love And Happiness", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Alok", "title": "Never Dull - Deep Down", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "American Authors", "title": "Best day of my life", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Andy Grammer", "title": "Keep Your Head Up", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Animal House", "title": "Otis Day The Knights - Shout", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "ATB x Topic x A7S", "title": "Your Love (9PM)", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Avicii", "title": "Levels", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Avicii", "title": "The Nights", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Avicii", "title": "Wake Me Up", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Avril Lavigne", "title": "Skater Boy", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Baby", "title": "Justin Bieber - Baby ft. Ludacris", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Backstreet Boys", "title": "Everybody", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Backstreet Boys I Want it that Way", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Beatles", "title": "Twist and Shout", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Bebe Rexha", "title": "Meant to Be (feat. Florida Georgia Line)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Becky G", "title": "Shower", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bee Gees", "title": "Stayin Alive (1977)", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Benny Blanco, Halsey Khalid", "title": "Eastside", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Better When I'm Dancing", "title": "Meghan Trainor - Better When Im Dancin", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Beyonce", "title": "Crazy In Love", "format": "m4a", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Beyonce", "title": "Single Ladies (Put A Ring On It)", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Bill Haley His Comets", "title": "Rock Around the Clock", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Billie Eilish", "title": "lovely ft. Khalid", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Billy Joel Uptown Girl with", "title": "Lyrics", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Blue", "title": "Eiffel 65 - Blue (Da Ba Dee)", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Blue Monday New Order", "title": "RemixSynth House", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Blue Swede", "title": "Hooked on a Feeling", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Blur", "title": "Song 2", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Bob Moses", "title": "Love Brand New", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bobby McFerrin", "title": "Dont Worry Be Happy", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bon Jovi", "title": "Its my life w", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Bon Jovi", "title": "Livin On A Prayer", "format": "m4a", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Boyfriend by Justin Bieber. CLEAN BEATS", "title": "", "format": "mp3", "category": "Pop", "cleanStatus": "Cleaned"},
  {"artist": "Brandy", "title": "Looking Glass (Youre a Fine Girl)", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "BRELAND", "title": "Praise The Lord (feat. Thomas Rhett)", "format": "m4a", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Bruno Mars", "title": "Count on Me", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bruno Mars", "title": "Grenade", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bruno Mars", "title": "Just The Way You Are", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bruno Mars", "title": "Marry You", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bruno Mars", "title": "Nothin On You - B.o.B - (feat. Bruno Mars)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Bruno MarsMark Ronson", "title": "Uptown Funk ft. Bruno Mars", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "BTS", "title": "Dynamite", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "BTS (방탄소년단) Butter Official", "title": "MV", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "BTS (방탄소년단) Permission to Dance Official", "title": "MV", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "C&C Music Factory", "title": "Good Vibrations", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Calvin Harris", "title": "Feel So Close", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Camila Cabello", "title": "Havana ft. Young Thug", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Carly Rae Jepsen", "title": "Call me maybe", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Caterina Valente", "title": "Bongo Cha Cha Cha Bongo la, bongo cha cha cha", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Cee Lo Green", "title": "Forget You Lyrics", "format": "m4a", "category": "Pop", "cleanStatus": "Cleaned"},
  {"artist": "Charlie Puth", "title": "We Dont Talk Anymore (feat. Selena Gomez)", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Chubby Checker", "title": "Lets Twist Again", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Chubby Checker-The", "title": "Twist", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Cmon N Ride It", "title": "(The Train)", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Coldplay", "title": "Higher Power", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Come On Eileen", "title": "Chris Thor Benfrancisco Remix FBM", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Cupid", "title": "Cupid Shuffle", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Cyndi Lauper", "title": "Girls Just Want To Have Fun - REMASTERED", "format": "m4a", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Dan+Shay", "title": "Speechless", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "David Guetta Bebe Rexha", "title": "Im Good", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "David Guetta Becky Hill Ella Henderson", "title": "Crazy What Love Can Do", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "David GuettaSia", "title": "Titanium", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Demi Lovato", "title": "Heart Attack", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Diplo", "title": "Forget About Me", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Dirty Dancing", "title": "Time of my life", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "DJ Casper", "title": "Cha Cha Slide", "format": "m4a", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "DJ Gotta ft Milky", "title": "Love Story (Remix)", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "DJ Khalid Skyline", "title": "Clean Edit - 42023, 2.13 PM", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "DJ Snake ft. Justin Bieber", "title": "Let Me Love You", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Drift Away By Uncle Kracker With", "title": "Lyrics", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Dua Lipa", "title": "Break My Heart", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Dua Lipa", "title": "Dont Start Now", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Dua Lipa", "title": "Levitating Featuring DaBaby", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Dua Lipa", "title": "Were Good", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Duke Jones x Louis", "title": "Jiggle Jiggle My Money Dont Jiggle Jiggle It Folds [TikTok Song]", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Ed Sheeran", "title": "2step (feat. Lil Baby)", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Ed Sheeran", "title": "Bad Habits", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Ed Sheeran Justin Bieber", "title": "I Dont Care", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Ed Sheeran", "title": "Perfect", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Ed Sheeran", "title": "Shivers -1", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Ed Sheeran", "title": "Thinking Out Loud", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Electric Slide", "title": "Line Dance -1", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Ellie Goulding", "title": "Lights", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Elton John, Dua Lipa", "title": "Cold Heart (PNAU Remix)", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Elvis Presley", "title": "Jailhouse Rock", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Fatboy Slim ft. Bootsy Collins", "title": "Weapon Of Choice", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Fleetwood Mac", "title": "Dreams", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "", "title": "Funkytown", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Gary Glitter Rock and Roll Pt. 2", "title": "", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Ghost", "title": "Justin Bieber - Ghost", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Glass Animals", "title": "Heat Waves", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Glass Animals", "title": "Heat Waves", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Gnarls Barkley", "title": "Crazy", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Goodnight Sweetheart Goodnight", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Green Day", "title": "Good Riddance (Time Of Your Life)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Grouplove", "title": "Tongue Tied Take me to your best friends house roll around this roundabout", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Haddaway", "title": "What Is Love (T-Mass Remix)", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Harlem Shake Baauer", "title": "Harlem Shake", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Harry Styles", "title": "Adore You", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Harry Styles", "title": "As It Was", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Harry Styles", "title": "Golden", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Heartless (feat. Morgan Wallen)", "title": "Clean Version", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "Here I Go Again (Radio Mix)", "format": "mp3", "category": "Rock", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "Hit Me With Your Best Shot (Remastered)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Hold My Hand", "title": "Hootie and the Blowfish - lyrics", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Hold On", "title": "Justin Bieber - Hold On", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "House Of Pain", "title": "Jump Around", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Cleaned"},
  {"artist": "HRVY", "title": "Personal", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "I Could Be The One (Avicii Vs. Nicky Romero) (Radio Edit)", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "I Dont Dance (From High School Musical 2Soundtrack Version)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "I Gotta Feeling - The Black Eyed Peas", "format": "mp3", "category": "Pop", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "I Like To Move It", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "I Really Like You", "title": "Carly Rae Jepsen", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Im Good (Blue)", "title": "Clean - David Guetta, Bebe Rexha Lyric", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "Imagine Dragons", "title": "Believer", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Imagine Dragons", "title": "Thunder", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Imagine Dragons x JID", "title": "Enemy", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Indestructable", "title": "Andy C Becky Hill - Indestructible", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Jackson 5", "title": "Blame It On the Boogie", "format": "m4a", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Jackson 5", "title": "I Want You Back", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "James Brown", "title": "I Feel Good", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Jason Aldean", "title": "Big Green Tractor", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Jason Derulo", "title": "Want to want me", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Jason Derulo", "title": "Acapulco", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Jason Mraz", "title": "Have it All", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Jason Mraz", "title": "I Feel Like Dancing", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Jason Mraz", "title": "I'm Yours", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Joel Corry MNEK", "title": "Head Heart", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "John Michael Montgomery", "title": "Be my baby tonight", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "John Michael Montgomery", "title": "I Like It, I Love It", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Jon Pardi", "title": "Dirt On My Boots", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Jon Pardi", "title": "Head Over Boots", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Jonas Blue", "title": "Why Dont We - Don’t Wake Me Up", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Jonas Blue", "title": "Mama ft. William Singe", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Jonas Blue", "title": "Rise ft. Jack Jack", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Jonas Brothers", "title": "Rollercoaster", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Jonas Brothers", "title": "Waffle House", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Josh Turner", "title": "Why Dont We Just Dance", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Journey", "title": "Dont Stop Believin", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Justin Timberlake", "title": "Can't Stop this feeling", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Justin Timberlake", "title": "Mirrors", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "K.C. and Sunshine Band", "title": "Boogie Shoes(Long Version)", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Kane Brown", "title": "Heaven", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Kane Brown", "title": "Thank God", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Kane Brown, Khalid, Swae Lee", "title": "Be Like That", "format": "mp3", "category": "Country", "cleanStatus": "Cleaned"},
  {"artist": "Kanye West", "title": "Heartless", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Kanye West", "title": "Hurricane ft. The Weeknd Lil Baby", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Kanye West", "title": "Moon ft. Kid Cudi Don Toliver", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Katrina & The Waves", "title": "Walking on Sunshine", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Katy Perry", "title": "Firework", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Katy Perry", "title": "Roar [Audio Only]", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Katy Perry", "title": "Smile", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Kelly Clarkson", "title": "Stronger", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Kenny Loggins", "title": "Footloose", "format": "m4a", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Khalid", "title": "Skyline (Instrumental)", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "Kung Fu Fighting", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Kygo", "title": "Dancing Feet ft. DNCE", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Kylie Minogue", "title": "The Loco-motion - Official", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Lady Gaga, Ariana Grande", "title": "Rain On Me", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Lemonade.Forrest Frank The Figs", "title": "Lemonade", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Lenny Kravitz", "title": "Fly Away", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Lil Durk", "title": "Broadway Girls ft. Morgan Wallen (Instrumental)", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Cleaned"},
  {"artist": "Lil Nas X", "title": "Old Town Road ft. Billy Ray Cyrus", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Little Mix", "title": "Word Up (Audio)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Livin' La Vida Loca", "title": "Ricky Martin - Livin La Vida Loca", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "LMFAO", "title": "Party Rock Anthem", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "Lose Yourself to Dance", "title": "Daft Punk (feat. Pharrell Williams)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Louie Louie", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Love Yourself", "title": "Justin Bieber - Love Yourself", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Lovefool", "title": "Cardigans", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Luke Combs", "title": "Beautiful Crazy", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Luke Combs", "title": "Fast Car", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "M.C. Hammer _ U Cant Touch This", "title": "(REMIX)", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Macklemore", "title": "Can't Hold Us", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Majestic", "title": "Time to Groove ft. Nonô", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Mark Ronson", "title": "Uptown Funk (Instrumental Original) ft. Bruno Mars", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Cleaned"},
  {"artist": "Marshmello Kane Brown", "title": "One Thing Right", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Marshmello ft. Bastille", "title": "Happier", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Marshmello, Kane Brown", "title": "One Thing Right", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Matt Stell", "title": "Prayed For You", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Meghan Trainor", "title": "Better when Im dancing LYRICS VIDEO", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Meghan Trainor", "title": "Like Im Gonna Lose You ft. John Legend", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Meghan Trainor", "title": "Made You Look", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Men Without Hats", "title": "Safety Dance (HD 720p)", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Michael Jackson", "title": "Don’t Stop Til You Get Enough", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Michael Jackson", "title": "Thriller", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Miley Cyrus", "title": "Flowers", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Miley Cyrus", "title": "Party In The U.S.A.", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Milli Vanilli", "title": "Blame It On the Rain", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "MKTO", "title": "Classic", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "MMMBop", "title": "-Hanson - MMMBop (Official Music Video)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "MMMBop Live", "title": "HANSON - MMMBop Live 25 Years Later", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "MmmBopDance", "title": "Hanson - mmmBop (House Remix) houseremix music remix reddit houseclassics dancemusic 90s", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Morgan Wallen", "title": "Diplo Heartless Very Clean Edit - 42023, 11.30 AM", "format": "mp3", "category": "Country", "cleanStatus": "Cleaned"},
  {"artist": "Morgan Wallen Clean Edit Broadway Girls Alone", "title": "- 42023, 1.31 PM", "format": "mp3", "category": "Country", "cleanStatus": "Cleaned"},
  {"artist": "Morgan Wallen", "title": "Cowgirls Clean Edit - 42023, 2.23 PM", "format": "mp3", "category": "Country", "cleanStatus": "Cleaned"},
  {"artist": "Mr C The Slide Man", "title": "Cha-Cha Slide", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Navigo", "title": "Where Are You Now", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Need Edit", "title": "Mark Ronson Bruno Mars - Uptown Funk (Clean -)", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Cleaned"},
  {"artist": "Need edit-Queen", "title": "Don’t Stop Me Now", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "needs slowed down", "title": "country roads", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Neil Diamond", "title": "Sweet Caroline", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Nelly Florida Georgia Line", "title": "Lil Bit (iHeartRadio Super Clean Edit)", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Cleaned"},
  {"artist": "Nelly Florida Georgia Line", "title": "Lil Bit (Radio Version) [Best Edit]", "format": "m4a", "category": "Hip-Hop", "cleanStatus": "Cleaned"},
  {"artist": "Nelly", "title": "Just A Dream", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "No Bad Vibes Jazzy x KILIMANJARO", "title": "No Bad Vibes", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "NSYNC", "title": "Bye Bye Bye", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Old Dominion", "title": "One Man Band", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "OMI", "title": "Cheerleader", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "Best Song Ever (Audio)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "Drag Me Down", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "Kiss You", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "Live While Were Young (Audio)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "One Thing", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "Steal My Girl (Audio)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "Story of My Life", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One Direction", "title": "What Makes You Beautiful", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One More Time", "title": "Daft Punk", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "One More Time- Daft Punk", "title": "One More Time", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "OneRepublic", "title": "Counting Stars 2", "format": "aif", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "OneRepublic", "title": "I Aint Worried", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "OneRepublic", "title": "You Were Loved", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Only Wanna Be With You", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Otis Day & The Knights", "title": "Shout", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Outkast", "title": "Hey Ya", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Owl City Carly Rae Jepsen", "title": "Good Time", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Owl City", "title": "Fireflies", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Owl City, Carly Rae Jepsen", "title": "Good Time", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Panic At the Disco", "title": "High Hopes 2", "format": "aif", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Panic At the Disco", "title": "High Hopes", "format": "aif", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Panic At the Disco", "title": "High Hopes", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Panic At The Disco", "title": "High Hopes", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Parmalee X Blanco Brown", "title": "Just The Way", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Pharrell Williams", "title": "Happy", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Pnk", "title": "Just Give Me a Reason", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Pnk, Willow Sage Hart", "title": "Cover Me In Sunshine", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Post Malone", "title": "Wrapped Around Your Finger", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Post Malone, Swae Lee", "title": "Sunflower (Spider-Man Into the Spider-Verse)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Praise You", "title": "Fatboy Slim - Praise You", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Prom 23 Arrival Track", "title": "5623, 6.58 PM", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "", "title": "Pump Up The Jam", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Queen", "title": "Another One Bites Remix", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Queen", "title": "Another One Bites The Dust", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Queen David Bowie", "title": "Under Pressure", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Queen", "title": "Somebody To Love", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Raining Tacos", "title": "Parry Gripp BooneBum", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Rascal Flatts", "title": "Life is a highway", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Rascal Flatts", "title": "My Wish", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Rasputin-Boney M.", "title": "Rasputin", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "RED BONE", "title": "Come and get your love (Subtitulado al español)", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Rednex", "title": "Cotton Eye Joe -", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Rednex", "title": "Cotton Eye Joe (HBz Bounce Remix)", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Rick Astley", "title": "Never Gonna Give You Up", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Ricky Desktop", "title": "The Chicken Wing Beat", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Rihanna", "title": "We Found Love ft. Calvin Harris", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Riton x Nightcrawlers ft. Mufasa Hypeman", "title": "Friday Dopamine Re-Edit", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "Rock This Town", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Rockafella Skank- Fatboy Slim", "title": "The Rockafeller Skank", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Russell Dickerson", "title": "Blue Tacoma", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Sam Hunt", "title": "Kinfolks (Medii Remix)", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Sam Hunt", "title": "Kinfolks", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Sam HuntFlo Rida", "title": "Mash-Up My House Party", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Shakira", "title": "Hips Dont Lie ft. Wyclef Jean", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Shania Twain", "title": "Giddy Up (MicroMix PJ edit)", "format": "mp3", "category": "Country", "cleanStatus": "Cleaned"},
  {"artist": "Shania Twain", "title": "Giddy Up", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Shawn Mendes", "title": "If I Cant Have You", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Shawn Mendes", "title": "Stitches", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Shawn Mendes", "title": "Theres Nothing Holding Me Back", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Shooting Stars", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Shut up and Dance", "title": "Walk The Moon - Shut up and dance", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Sia", "title": "Cheap Thrills ft. Sean Paul", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Silentó", "title": "Watch Me (WhipNae Nae)", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Skillet", "title": "Undefeated", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Skrillex and Diplo", "title": "Where Are Ü Now with Justin Bieber", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Smash Mouth", "title": "All Star (HQ)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Smash Mouth", "title": "Im A Believer", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "SOFI TUKKER", "title": "Summer In New York [Ultra Records]", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Soft Cell", "title": "Tainted Love ( White House Remix )", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Sorry", "title": "Justin Bieber - Sorry", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Spin Doctors", "title": "Two Princes", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Standy Marc Korn", "title": "You Spin Me Round (Like A Record)", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Steve Lacey", "title": "Dark Red", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Stuck in the Moment", "title": "Justin Bieber Lyrics (My World 2.0 Studio Version)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Summer", "title": "Calvin Harris", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Summettime blues", "title": "Chris Lake, Sammy Virji, Nathan Nicholson - Summertime Blues", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Taio Cruz", "title": "Break Your Heart ft. Ludacris", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taio Cruz", "title": "Dynamite", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taka.Skrillex, Ahadadream, Priya Ragu", "title": "TAKA", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Taylor Swift", "title": "22", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taylor Swift", "title": "I Knew You Were Trouble", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taylor Swift", "title": "I Wish You Would", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taylor Swift", "title": "Shake it Off", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taylor Swift", "title": "We Are Never Ever Getting Back Together", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Taylor Swift", "title": "You Belong to Me", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Tears For Fears", "title": "Everybody Wants To Rule The World", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "The B-52s", "title": "Private Idaho", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "The Bangles", "title": "Walk Like an Egyptian", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "", "title": "The Black Eyed Peas Lets Get It Started Clean", "format": "mp3", "category": "Pop", "cleanStatus": "Cleaned"},
  {"artist": "The Chainsmokers Coldplay", "title": "Something Just Like This", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "The Greatest Showman Cast", "title": "This Is Me", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "The Isley Brothers", "title": "Shout Lyrics", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "The Killers", "title": "Mr. Brightside", "format": "m4a", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "The Romantics", "title": "What I Like About You (Remastered) Hq", "format": "m4a", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "The Script", "title": "Hall Of Fame", "format": "m4a", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "The Sugarhill Gang-Rapper´s Delight Remix Dj gurge", "title": "", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "The Village People", "title": "Y.M.C.A.", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "The Wanted", "title": "Glad You Came", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "The Weeknd", "title": "Blinding Lights", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "The Weeknd", "title": "Save Your Tears", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "This Is What You Came For", "title": "Calvin Harris (Feat. Rihanna)", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Thomas Rhett Crash And Burn", "title": "Lyrics", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "THRILLER", "title": "DUBSTEP RICARDO WALKER MARIE POPPINS", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Tom Jones", "title": "Its Not Unusual (With Lyrics)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Tones and I", "title": "Dance Monkey", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Too Many Zooz, KDA", "title": "So Real (Warriors) ft. Jess Glynne", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "", "title": "Turn Down For What", "format": "mp3", "category": "EDM", "cleanStatus": "Cleaned"},
  {"artist": "Tyler Hubbard", "title": "Dancin’ In The Country", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "U Can' t Touch This", "title": "MC Hammer - You cant touch this BUGG", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Uptown Funk UltraClean", "title": "Bruno Mars", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Cleaned"},
  {"artist": "Usher Dj got us falling in love again", "title": "5523, 2.57 PM", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Vanilla Ice Ice Ice Baby Remix Music", "title": "Video", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Vanilla ice", "title": "Ice ice baby", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Video Killed The Radio Star", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "", "title": "Wake Me up Before You Go-Go", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Walker Hayes", "title": "Fancy Like (Remix) Ft. Kesha-1", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Walker Hayes", "title": "Fancy Like", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Walker Hayes", "title": "Fancy Remix", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Warren G", "title": "Regulate ft. Nate Dogg (Instrumental)", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Cleaned"},
  {"artist": "Weezer", "title": "Africa", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Weezer", "title": "Island In The Sun", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Wham", "title": "Wake Me Up Before You Go-Go (Bass Boosted)", "format": "m4a", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "What is Love-Haddaway", "title": "What Is Love [Official 4K]", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Whatever- Kygo, Ava Max", "title": "Whatever", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Where are U Now-Skrillex, Diplo, Justin Bieber", "title": "Where Are U Now", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "White Stripes", "title": "Seven Nation Army - Lyrics Scrolling", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Whitney Houston", "title": "How Will I Know (Live from Welcome Home Heroes with Whitney Houston)", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Whitney Houston", "title": "I Wanna Dance With Somebody", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Whitney Houston, Clean Bandit", "title": "How Will I Know", "format": "m4a", "category": "R&B/Soul/Disco", "cleanStatus": "Clean"},
  {"artist": "Will Smith", "title": "Gettin Jiggy Wit It", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Will Smith", "title": "Men In Black (Video Version)", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Usher ft. Ludacris Lil Jon", "title": "Yeah [Extra Clean]", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Cleaned"},
  {"artist": "", "title": "You Spin Me Round (Like A Record)", "format": "mp3", "category": "New Wave/80s", "cleanStatus": "Clean"},
  {"artist": "Youngblood", "title": "5 Seconds Of Summer", "format": "m4a", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "", "title": "Your Mama Dont Dance Loggins and Messina Lyrics ☾☀", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Zedd", "title": "Clarity", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Zedd", "title": "I Want You To Know ft. Selena Gomez", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Zedd, Grey", "title": "The Middle ft. Maren Morris", "format": "m4a", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "Zombie Nation", "title": "Kernkraft 400 (HQ)", "format": "mp3", "category": "EDM", "cleanStatus": "Clean"},
  {"artist": "24k.UptownMash Clean", "title": "Bruno Mars - 92325, 3.24 PM", "format": "mp3", "category": "R&B/Soul/Disco", "cleanStatus": "Cleaned"},
  {"artist": "300 Violin Orchestra", "title": "Jorge Quintero", "format": "mp3", "category": "Instrumental", "cleanStatus": "Clean"},
  {"artist": "", "title": "500 Miles Im Gonna Be", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Abba", "title": "Dancing Queen (Official Music Video Remastered)", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Baha Men", "title": "Who Let The Dogs Out", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Billy Ray Cyrus", "title": "Achy Breaky Heart", "format": "mp3", "category": "Country", "cleanStatus": "Clean"},
  {"artist": "Ray Parker Jr.", "title": "Ghostbusters", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Michael Jackson", "title": "Smooth Criminal", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "Traditional", "title": "Chicken Dance", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Gloria Estefan", "title": "Conga", "format": "mp3", "category": "Latin/Pop", "cleanStatus": "Clean"},
  {"artist": "PSY", "title": "Gangnam Style", "format": "mp3", "category": "Pop", "cleanStatus": "Clean"},
  {"artist": "iLoveMemphis", "title": "Hit the Quan", "format": "mp3", "category": "Hip-Hop", "cleanStatus": "Clean"},
  {"artist": "Bobby Pickett", "title": "Monster Mash", "format": "mp3", "category": "Oldies", "cleanStatus": "Clean"},
  {"artist": "Ice Age Cast", "title": "Sid Shuffle", "format": "mp3", "category": "Other", "cleanStatus": "Clean"},
  {"artist": "Traditional", "title": "Hokey Pokey", "format": "mp3", "category": "Dance/Line", "cleanStatus": "Clean"},
  {"artist": "Survivor", "title": "Eye of the Tiger (Remix)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Europe", "title": "The Final Countdown (Remix)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"},
  {"artist": "Ozzy Osbourne", "title": "Crazy Train (Remix)", "format": "mp3", "category": "Rock", "cleanStatus": "Clean"}
];
